import { PrismaClient } from '@prisma/client'

const prisma = new PrismaClient()

async function main() {
  console.log('Starting database seeding...')

  // Seed Countries
  const countries = [
    {
      name: 'Canada',
      code: 'CA',
      flagUrl: '/flags/ca.svg',
      regions: [
        'Alberta', 'British Columbia', 'Manitoba', 'New Brunswick', 'Newfoundland and Labrador',
        'Northwest Territories', 'Nova Scotia', 'Nunavut', 'Ontario', 'Prince Edward Island',
        'Quebec', 'Saskatchewan', 'Yukon'
      ]
    },
    {
      name: 'Mexico',
      code: 'MX',
      flagUrl: '/flags/mx.svg',
      regions: [
        'Aguascalientes', 'Baja California', 'Baja California Sur', 'Campeche', 'Chiapas',
        'Chihuahua', 'Ciudad de Mexico', 'Coahuila', 'Colima', 'Durango', 'Guanajuato',
        'Guerrero', 'Hidalgo', 'Jalisco', 'Mexico State', 'Michoacán', 'Morelos', 'Nayarit',
        'Nuevo León', 'Oaxaca', 'Puebla', 'Querétaro', 'Quintana Roo', 'San Luis Potosí',
        'Sinaloa', 'Sonora', 'Tabasco', 'Tamaulipas', 'Tlaxcala', 'Veracruz', 'Yucatán', 'Zacatecas'
      ]
    },
    {
      name: 'United States',
      code: 'US',
      flagUrl: '/flags/us.svg',
      regions: [
        'Alabama', 'Alaska', 'Arizona', 'Arkansas', 'California', 'Colorado', 'Connecticut',
        'Delaware', 'Florida', 'Georgia', 'Hawaii', 'Idaho', 'Illinois', 'Indiana', 'Iowa',
        'Kansas', 'Kentucky', 'Louisiana', 'Maine', 'Maryland', 'Massachusetts', 'Michigan',
        'Minnesota', 'Mississippi', 'Missouri', 'Montana', 'Nebraska', 'Nevada', 'New Hampshire',
        'New Jersey', 'New Mexico', 'New York', 'North Carolina', 'North Dakota', 'Ohio',
        'Oklahoma', 'Oregon', 'Pennsylvania', 'Rhode Island', 'South Carolina', 'South Dakota',
        'Tennessee', 'Texas', 'Utah', 'Vermont', 'Virginia', 'Washington', 'West Virginia',
        'Wisconsin', 'Wyoming'
      ]
    }
  ]

  for (const country of countries) {
    await prisma.country.upsert({
      where: { code: country.code },
      update: {},
      create: country
    })
  }

  // Seed Events
  const events = [
    {
      id: 1000,
      name: 'Bear Hug: Live in Concert',
      date: 'May 20, 2024',
      time: '10 PM',
      location: 'Harmony Theater, Winnipeg, MB',
      totalRevenue: '$102,552',
      totalRevenueChange: '+3.2%',
      ticketsAvailable: 500,
      ticketsSold: 350,
      ticketsSoldChange: '+8.1%',
      pageViews: '24,300',
      pageViewsChange: '-0.75%',
      status: 'On Sale',
      imgUrl: '/events/bear-hug.jpg',
      thumbUrl: '/events/bear-hug-thumb.jpg',
    },
    {
      id: 1001,
      name: 'Six Fingers — DJ Set',
      date: 'Jun 2, 2024',
      time: '8 PM',
      location: 'Moonbeam Arena, Uxbridge, ON',
      totalRevenue: '$24,115',
      totalRevenueChange: '+3.2%',
      ticketsAvailable: 150,
      ticketsSold: 72,
      ticketsSoldChange: '+8.1%',
      pageViews: '57,544',
      pageViewsChange: '-2.5%',
      status: 'On Sale',
      imgUrl: '/events/six-fingers.jpg',
      thumbUrl: '/events/six-fingers-thumb.jpg',
    },
    {
      id: 1002,
      name: 'We All Look The Same',
      date: 'Aug 5, 2024',
      time: '4 PM',
      location: 'Electric Coliseum, New York, NY',
      totalRevenue: '$40,598',
      totalRevenueChange: '+3.2%',
      ticketsAvailable: 275,
      ticketsSold: 275,
      ticketsSoldChange: '+8.1%',
      pageViews: '122,122',
      pageViewsChange: '-8.0%',
      status: 'Closed',
      imgUrl: '/events/we-all-look-the-same.jpg',
      thumbUrl: '/events/we-all-look-the-same-thumb.jpg',
    },
    {
      id: 1003,
      name: 'Viking People',
      date: 'Dec 31, 2024',
      time: '8 PM',
      location: 'Tapestry Hall, Cambridge, ON',
      totalRevenue: '$3,552',
      totalRevenueChange: '+3.2%',
      ticketsAvailable: 40,
      ticketsSold: 6,
      ticketsSoldChange: '+8.1%',
      pageViews: '9,000',
      pageViewsChange: '-0.15%',
      status: 'On Sale',
      imgUrl: '/events/viking-people.jpg',
      thumbUrl: '/events/viking-people-thumb.jpg',
    },
  ]

  for (const event of events) {
    await prisma.event.upsert({
      where: { id: event.id },
      update: {},
      create: event
    })
  }

  // Seed Customers
  const customers = [
    {
      id: 1,
      name: 'Leslie Alexander',
      email: 'leslie.alexander@example.com',
      address: '123 Main St. Toronto, ON',
      country: 'Canada',
      countryCode: 'CA',
      flagUrl: '/flags/ca.svg',
    },
    {
      id: 2,
      name: 'Michael Foster',
      email: 'michael.foster@example.com',
      address: '357 Bridge St. New York, NY',
      country: 'USA',
      countryCode: 'US',
      flagUrl: '/flags/us.svg',
    },
    {
      id: 3,
      name: 'Dries Vincent',
      email: 'dries.vincent@example.com',
      address: '456 Elm St. Vancouver, BC',
      country: 'Canada',
      countryCode: 'CA',
      flagUrl: '/flags/ca.svg',
    },
    {
      id: 4,
      name: 'Lindsay Walton',
      email: 'lindsay.walton@example.com',
      address: '789 Oak St. Montreal, QC',
      country: 'Canada',
      countryCode: 'CA',
      flagUrl: '/flags/ca.svg',
    },
    {
      id: 5,
      name: 'Courtney Henry',
      email: 'courtney.henry@example.com',
      address: '321 Pine St. Calgary, AB',
      country: 'Canada',
      countryCode: 'CA',
      flagUrl: '/flags/ca.svg',
    },
    {
      id: 6,
      name: 'Tom Cook',
      email: 'tom.cook@example.com',
      address: '741 Lake St. Miami, FL',
      country: 'USA',
      countryCode: 'US',
      flagUrl: '/flags/us.svg',
    },
    {
      id: 7,
      name: 'Whitney Francis',
      email: 'whitney.francis@example.com',
      address: '654 Maple St. Ottawa, ON',
      country: 'Canada',
      countryCode: 'CA',
      flagUrl: '/flags/ca.svg',
    },
    {
      id: 8,
      name: 'Leonard Krasner',
      email: 'leonard.krasner@example.com',
      address: '987 Birch St. Winnipeg, MB',
      country: 'Canada',
      countryCode: 'CA',
      flagUrl: '/flags/ca.svg',
    },
    {
      id: 9,
      name: 'Floyd Miles',
      email: 'floyd.miles@example.com',
      address: '147 Cedar St. Quebec City, QC',
      country: 'Canada',
      countryCode: 'CA',
      flagUrl: '/flags/ca.svg',
    },
    {
      id: 10,
      name: 'Emily Selman',
      email: 'emily.selman@example.com',
      address: '258 Willow St. Halifax, NS',
      country: 'Canada',
      countryCode: 'CA',
      flagUrl: '/flags/ca.svg',
    },
    {
      id: 11,
      name: 'Kristin Watson',
      email: 'kristin.watson@example.com',
      address: '369 Spruce St. Edmonton, AB',
      country: 'Canada',
      countryCode: 'CA',
      flagUrl: '/flags/ca.svg',
    },
    {
      id: 12,
      name: 'Emma Dorsey',
      email: 'emma.dorsey@example.com',
      address: '159 Park St. Chicago, IL',
      country: 'USA',
      countryCode: 'US',
      flagUrl: '/flags/us.svg',
    },
    {
      id: 13,
      name: 'Alicia Bell',
      email: 'alicia.bell@example.com',
      address: '741 Laurel St. Regina, SK',
      country: 'Canada',
      countryCode: 'CA',
      flagUrl: '/flags/ca.svg',
    },
    {
      id: 14,
      name: 'Jenny Wilson',
      email: 'jenny.wilson@example.com',
      address: '852 Ash St. Saskatoon, SK',
      country: 'Canada',
      countryCode: 'CA',
      flagUrl: '/flags/ca.svg',
    },
    {
      id: 15,
      name: 'Anna Roberts',
      email: 'anna.roberts@example.com',
      address: '852 Hill St. Houston, TX',
      country: 'USA',
      countryCode: 'US',
      flagUrl: '/flags/us.svg',
    },
    {
      id: 16,
      name: 'Benjamin Russel',
      email: 'benjamin.russel@example.com',
      address: '963 Cherry St. Victoria, BC',
      country: 'Canada',
      countryCode: 'CA',
      flagUrl: '/flags/ca.svg',
    },
    {
      id: 17,
      name: 'Jeffrey Webb',
      email: 'jeffrey.webb@example.com',
      address: '654 Ocean St. Hamilton, ON',
      country: 'Canada',
      countryCode: 'CA',
      flagUrl: '/flags/ca.svg',
    },
    {
      id: 18,
      name: 'Kathryn Murphy',
      email: 'kathryn.murphy@example.com',
      address: '357 River St. London, ON',
      country: 'Canada',
      countryCode: 'CA',
      flagUrl: '/flags/ca.svg',
    },
    {
      id: 19,
      name: 'Lawrence Hunter',
      email: 'lawrence.hunter@example.com',
      address: '159 Lake St. Mississauga, ON',
      country: 'Canada',
      countryCode: 'CA',
      flagUrl: '/flags/ca.svg',
    },
    {
      id: 20,
      name: 'Yvette Armstrong',
      email: 'yvette.armstrong@example.com',
      address: '852 Forest St. Markham, ON',
      country: 'Canada',
      countryCode: 'CA',
      flagUrl: '/flags/ca.svg',
    },
    {
      id: 21,
      name: 'Angela Fisher',
      email: 'angela.fisher@example.com',
      address: '741 Hill St. Brampton, ON',
      country: 'Canada',
      countryCode: 'CA',
      flagUrl: '/flags/ca.svg',
    },
    {
      id: 22,
      name: 'Blake Reid',
      email: 'blake.reid@example.com',
      address: '369 Valley St. Oshawa, ON',
      country: 'Canada',
      countryCode: 'CA',
      flagUrl: '/flags/ca.svg',
    },
    {
      id: 23,
      name: 'Hector Gibbons',
      email: 'hector.gibbons@example.com',
      address: '258 Ridge St. Richmond Hill, ON',
      country: 'Canada',
      countryCode: 'CA',
      flagUrl: '/flags/ca.svg',
    },
    {
      id: 24,
      name: 'Fabricio Mendes',
      email: 'fabricio.mendes@example.com',
      address: '147 Park St. Vaughan, ON',
      country: 'Canada',
      countryCode: 'CA',
      flagUrl: '/flags/ca.svg',
    },
    {
      id: 25,
      name: 'Jillian Steward',
      email: 'jillian.steward@example.com',
      address: '987 Grove St. Windsor, ON',
      country: 'Canada',
      countryCode: 'CA',
      flagUrl: '/flags/ca.svg',
    },
    {
      id: 26,
      name: 'Chelsea Hagon',
      email: 'chelsea.hagon@example.com',
      address: '654 Court St. Los Angeles, CA',
      country: 'USA',
      countryCode: 'US',
      flagUrl: '/flags/us.svg',
    }
  ]

  for (const customer of customers) {
    await prisma.customer.upsert({
      where: { id: customer.id },
      update: {},
      create: customer
    })
  }

  // Seed orders
  const orders = [
    {
      id: 3000,
      date: 'May 9, 2024',
      amountUsd: '$80.00',
      amountCad: '$109.47',
      fee: '$3.28',
      net: '$106.19',
      transactionId: 'ch_2HLf8DfYJ0Db7asfCC5T546TY',
      customerId: 1,
      eventId: 1000,
    },
    {
      id: 3001,
      date: 'May 5, 2024',
      amountUsd: '$299.00',
      amountCad: '$409.13',
      fee: '$12.27',
      net: '$396.86',
      transactionId: 'ch_1KLf7AsYJ0Dda7fs3CC5d46TY',
      customerId: 2,
      eventId: 1001,
    },
    {
      id: 3002,
      date: 'Apr 28, 2024',
      amountUsd: '$150.00',
      amountCad: '$205.25',
      fee: '$6.15',
      net: '$199.10',
      transactionId: 'ch_2DLf5AsYJ0Ddb7fs3CC5d46TY',
      customerId: 3,
      eventId: 1002,
    },
    {
      id: 3003,
      date: 'Apr 23, 2024',
      amountUsd: '$80.00',
      amountCad: '$109.47',
      fee: '$3.28',
      net: '$106.19',
      transactionId: 'ch_3KLf6AsYJ0Ddb7fs3CC5d46TY',
      customerId: 4,
      eventId: 1000,
    },
    {
      id: 3004,
      date: 'Apr 18, 2024',
      amountUsd: '$114.99',
      amountCad: '$157.34',
      fee: '$4.72',
      net: '$152.62',
      transactionId: 'ch_4HLf7DfYJ0Db78fas3C5d6TY',
      customerId: 5,
      eventId: 1003,
    },
    {
      id: 3005,
      date: 'Apr 14, 2024',
      amountUsd: '$299.00',
      amountCad: '$409.13',
      fee: '$12.27',
      net: '$396.86',
      transactionId: 'ch_5HLf8DfYJ0Ddb78fas3CC5TY',
      customerId: 6,
      eventId: 1001,
    },
    {
      id: 3006,
      date: 'Apr 10, 2024',
      amountUsd: '$150.00',
      amountCad: '$205.25',
      fee: '$6.15',
      net: '$199.10',
      transactionId: 'ch_6KLf9DfYJ0Db7asf3CC54dTY',
      customerId: 7,
      eventId: 1002,
    },
    {
      id: 3007,
      date: 'Apr 6, 2024',
      amountUsd: '$80.00',
      amountCad: '$109.47',
      fee: '$3.28',
      net: '$106.19',
      transactionId: 'ch_7KLf6DfYJ0Ddb78fs3C5d6TY',
      customerId: 8,
      eventId: 1000,
    },
    {
      id: 3008,
      date: 'Apr 3, 2024',
      amountUsd: '$80.00',
      amountCad: '$109.47',
      fee: '$3.28',
      net: '$106.19',
      transactionId: 'ch_8HLf5AsYJ0Db78fassCC5d6TY',
      customerId: 9,
      eventId: 1000,
    },
    {
      id: 3009,
      date: 'Mar 29, 2024',
      amountUsd: '$114.99',
      amountCad: '$157.34',
      fee: '$4.72',
      net: '$152.62',
      transactionId: 'ch_9KLf7DfYJ0Ddb78fas3C5dTY',
      customerId: 10,
      eventId: 1003,
    },
    {
      id: 3010,
      date: 'Mar 25, 2024',
      amountUsd: '$299.00',
      amountCad: '$409.13',
      fee: '$12.27',
      net: '$396.86',
      transactionId: 'ch_1KLf8DfYJ0Db78fas3CC54TY',
      customerId: 11,
      eventId: 1001,
    },
    {
      id: 3011,
      date: 'Mar 21, 2024',
      amountUsd: '$80.00',
      amountCad: '$109.47',
      fee: '$3.28',
      net: '$106.19',
      transactionId: 'ch_2KLf9DfYJ0Db78fas3CC546Y',
      customerId: 12,
      eventId: 1000,
    },
    {
      id: 3012,
      date: 'Mar 16, 2024',
      amountUsd: '$150.00',
      amountCad: '$205.25',
      fee: '$6.15',
      net: '$199.10',
      transactionId: 'ch_3HLf6DfYJ0Db7afs3CC54dTY',
      customerId: 13,
      eventId: 1002,
    },
    {
      id: 3013,
      date: 'Mar 12, 2024',
      amountUsd: '$299.00',
      amountCad: '$409.13',
      fee: '$12.27',
      net: '$396.86',
      transactionId: 'ch_4DLf7DfYJ0Db78fs3CC5d46Y',
      customerId: 14,
      eventId: 1001,
    },
    {
      id: 3014,
      date: 'Mar 8, 2024',
      amountUsd: '$150.00',
      amountCad: '$205.25',
      fee: '$6.15',
      net: '$199.10',
      transactionId: 'ch_5KLf8DfYJ0Db78fssCC54TY',
      customerId: 15,
      eventId: 1002,
    },
    {
      id: 3015,
      date: 'Mar 4, 2024',
      amountUsd: '$150.00',
      amountCad: '$205.25',
      fee: '$6.15',
      net: '$199.10',
      transactionId: 'ch_6HLf9DfYJ0Db78fas3CC546TY',
      customerId: 16,
      eventId: 1002,
    },
    {
      id: 3016,
      date: 'Feb 28, 2024',
      amountUsd: '$80.00',
      amountCad: '$109.47',
      fee: '$3.28',
      net: '$106.19',
      transactionId: 'ch_7HLf6DfYJ0Db78fas3CC546Y',
      customerId: 17,
      eventId: 1000,
    },
    {
      id: 3017,
      date: 'Feb 23, 2024',
      amountUsd: '$80.00',
      amountCad: '$109.47',
      fee: '$3.28',
      net: '$106.19',
      transactionId: 'ch_8KLf5DfYJ0Db78fas3CC546TY',
      customerId: 18,
      eventId: 1000,
    },
    {
      id: 3018,
      date: 'Feb 19, 2024',
      amountUsd: '$114.99',
      amountCad: '$157.34',
      fee: '$4.72',
      net: '$152.62',
      transactionId: 'ch_9HLf8DfYJ0Db78fas3CC5dTY',
      customerId: 19,
      eventId: 1003,
    },
    {
      id: 3019,
      date: 'Feb 15, 2024',
      amountUsd: '$114.99',
      amountCad: '$157.34',
      fee: '$4.72',
      net: '$152.62',
      transactionId: 'ch_1HLf9DfYJ0Db78fas3CC54TY',
      customerId: 20,
      eventId: 1003,
    },
    {
      id: 3020,
      date: 'Feb 10, 2024',
      amountUsd: '$299.00',
      amountCad: '$409.13',
      fee: '$12.27',
      net: '$396.86',
      transactionId: 'ch_2DLf6DfYJ0Db78fas3CC546TY',
      customerId: 21,
      eventId: 1001,
    },
    {
      id: 3021,
      date: 'Feb 5, 2024',
      amountUsd: '$80.00',
      amountCad: '$109.47',
      fee: '$3.28',
      net: '$106.19',
      transactionId: 'ch_3KLf5DfYJ0Db78fassCC546TY',
      customerId: 22,
      eventId: 1000,
    },
    {
      id: 3022,
      date: 'Feb 1, 2024',
      amountUsd: '$114.99',
      amountCad: '$157.34',
      fee: '$4.72',
      net: '$152.62',
      transactionId: 'ch_4HLf8DfYJ0Db78fas3CC546Y',
      customerId: 23,
      eventId: 1003,
    },
    {
      id: 3023,
      date: 'Jan 27, 2024',
      amountUsd: '$114.99',
      amountCad: '$157.34',
      fee: '$4.72',
      net: '$152.62',
      transactionId: 'ch_5KLf9DfYJ0Db78fs3CC546TY',
      customerId: 24,
      eventId: 1003,
    },
    {
      id: 3024,
      date: 'Jan 22, 2024',
      amountUsd: '$114.99',
      amountCad: '$157.34',
      fee: '$4.72',
      net: '$152.62',
      transactionId: 'ch_6HLf6DfYJ0Db78fas3CC5dTY',
      customerId: 25,
      eventId: 1003,
    },
    {
      id: 3025,
      date: 'Jan 18, 2024',
      amountUsd: '$114.99',
      amountCad: '$157.34',
      fee: '$4.72',
      net: '$152.62',
      transactionId: 'ch_7HLf7DfYJ0Db78fas3CC546TY',
      customerId: 26,
      eventId: 1003,
    },
  ]

  for (const order of orders) {
    await prisma.order.upsert({
      where: { id: order.id },
      update: {},
      create: order
    })
  }

  // Seed payments
  const payments = [
    {
      orderId: 3000,
      cardNumber: '1254',
      cardType: 'American Express',
      cardExpiry: '01 / 2025',
    },
    {
      orderId: 3001,
      cardNumber: '3897',
      cardType: 'Visa',
      cardExpiry: '06 / 2024',
    },
    {
      orderId: 3002,
      cardNumber: '7421',
      cardType: 'Mastercard',
      cardExpiry: '12 / 2026',
    },
    {
      orderId: 3003,
      cardNumber: '5683',
      cardType: 'Visa',
      cardExpiry: '06 / 2024',
    },
    {
      orderId: 3004,
      cardNumber: '9576',
      cardType: 'Visa',
      cardExpiry: '01 / 2025',
    },
    {
      orderId: 3005,
      cardNumber: '2310',
      cardType: 'Visa',
      cardExpiry: '08 / 2024',
    },
    {
      orderId: 3006,
      cardNumber: '6942',
      cardType: 'Mastercard',
      cardExpiry: '06 / 2024',
    },
    {
      orderId: 3007,
      cardNumber: '8473',
      cardType: 'Visa',
      cardExpiry: '08 / 2024',
    },
    {
      orderId: 3008,
      cardNumber: '5061',
      cardType: 'Visa',
      cardExpiry: '11 / 2026',
    },
    {
      orderId: 3009,
      cardNumber: '3129',
      cardType: 'American Express',
      cardExpiry: '06 / 2025',
    },
    {
      orderId: 3010,
      cardNumber: '6498',
      cardType: 'Visa',
      cardExpiry: '06 / 2024',
    },
    {
      orderId: 3011,
      cardNumber: '1732',
      cardType: 'American Express',
      cardExpiry: '08 / 2024',
    },
    {
      orderId: 3012,
      cardNumber: '8256',
      cardType: 'Visa',
      cardExpiry: '01 / 2024',
    },
    {
      orderId: 3013,
      cardNumber: '4901',
      cardType: 'Mastercard',
      cardExpiry: '06 / 2025',
    },
    {
      orderId: 3014,
      cardNumber: '7365',
      cardType: 'Visa',
      cardExpiry: '06 / 2024',
    },
    {
      orderId: 3015,
      cardNumber: '2849',
      cardType: 'Visa',
      cardExpiry: '06 / 2024',
    },
    {
      orderId: 3016,
      cardNumber: '6132',
      cardType: 'Mastercard',
      cardExpiry: '01 / 2026',
    },
    {
      orderId: 3017,
      cardNumber: '9054',
      cardType: 'Mastercard',
      cardExpiry: '06 / 2024',
    },
    {
      orderId: 3018,
      cardNumber: '4287',
      cardType: 'Mastercard',
      cardExpiry: '06 / 2024',
    },
    {
      orderId: 3019,
      cardNumber: '1765',
      cardType: 'Visa',
      cardExpiry: '06 / 2025',
    },
    {
      orderId: 3020,
      cardNumber: '5923',
      cardType: 'Visa',
      cardExpiry: '12 / 2024',
    },
    {
      orderId: 3021,
      cardNumber: '3014',
      cardType: 'Visa',
      cardExpiry: '06 / 2024',
    },
    {
      orderId: 3022,
      cardNumber: '8642',
      cardType: 'American Express',
      cardExpiry: '11 / 2026',
    },
    {
      orderId: 3023,
      cardNumber: '5173',
      cardType: 'Visa',
      cardExpiry: '12 / 2025',
    },
    {
      orderId: 3024,
      cardNumber: '6298',
      cardType: 'Mastercard',
      cardExpiry: '06 / 2024',
    },
    {
      orderId: 3025,
      cardNumber: '9401',
      cardType: 'American Express',
      cardExpiry: '08 / 2025',
    },
  ]

  for (const payment of payments) {
    await prisma.payment.upsert({
      where: { orderId: payment.orderId },
      update: {},
      create: payment
    })
  }

  console.log('Database seeding completed!')
}

main()
  .then(async () => {
    await prisma.$disconnect()
  })
  .catch(async (e) => {
    console.error(e)
    await prisma.$disconnect()
    process.exit(1)
  })
